version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Japan
  labels:
  - dependencies
  allow:
  - dependency-type: "production"
  commit-message:
    prefix: deps

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "cicd"
  commit-message:
    prefix: ci
